var realNames = {
  "aisling@pebblecode.com": "Aisling Foley",
  "alex@pebblecode.com": "Alex Butcher",
  "allan@pebblecode.com": "Allan Ward",
  "andy.wardle@pebblecode.com": "Andy Wardle",
  "cheng@pebblecode.com": "Cheng Cui",
  "elia.kim@pebblecode.com": "Elia Kim",
  "emma.nash@pebblecode.com": "Emma Nash",
  "fergus@pebblecode.com": "Fergus Hynd",
  "francesca@pebbleit.com": "Francesca Galluzo",
  "george@pebblecode.com": "George Ornbo",
  "ian.black@pebblecode.com": "Ian Black",
  "james.wallace@pebblecode.com": "James Wallace",
  "jaz@pebblecode.com": "Jaz Lalli",
  "joe.fitter@pebblecode.com": "Joe Fitter",
  "john@pebblecode.com": "John Mildinhall",
  "jonny@pebblecode.com": "Jonny Li",
  "joseph@pebblecode.com": "Joseph Jeganthan",
  "mark@pebblecode.com": "Mark Durrant",
  "martin.schinz@pebblecode.com": "Martin Schinz",
  "niall@pebblecode.com": "Niall Henn",
  "paul@pebbleit.com": "Paul Addicott-Evans",
  "peter.tait@pebblecode.com": "Peter Tait",
  "sam@pebblecode.com": "Sam Desborough",
  "saverio.castelli@pebblecode.com": "Saverio Castelli",
  "simon.white@pebblecode.com": "Simon White",
  "tane.piper@pebblecode.com": "Tane Piper",
  "toby@pebblecode.com": "Toby Hunt",
  "will@pebbleit.com": "Will Stanway"
};

module.exports = realNames;
